### ISSUE TITLE
Not able to create hierarchical sub tenant

### ISSUE THREAD

**Issue by pradeepgururani** [JonPSmith/AuthPermissions.AspNetCore#103]
We are trying setup multi level tenant app with sharding. We are using the latest version of library. Net framework is 8.0 and DB is postgres.

Following is AuthP configuration:

```
webApplicationBuilder.Services.RegisterAuthPermissions<AquaPermissions>(options =>
    {
      options.TenantType = TenantTypes.HierarchicalTenant;
      ...
      ...
    })
    .UsingEfCorePostgres(identityConnectionString)
    .SetupMultiTenantSharding(new ShardingEntryOptions(false))
    .IndividualAccountsAuthentication()
    .RegisterAddClaimToUser<AddTenantNameClaim>()
    .RegisterTenantChangeService<AquaTenantChangeService>()
    .AddSuperUserToIndividualAccounts()
    .SetupAspNetCoreAndDatabase(options =>
    {
      //Migrate individual account database
      options.RegisterServiceToRunInJob<StartupServiceMigrateAnyDbContext<AquaIdentityContext>>();
      //Add demo users to the database
      options.RegisterServiceToRunInJob<StartupServicesIndividualAccountsAddDemoUsers>();

      //Migrate the application part of the database
      options.RegisterServiceToRunInJob<StartupServiceMigrateAnyDbContext<AquaAppContext>>();
    });
```

We are using `IAuthTenantAdminService.AddHierarchicalTenantAsync` to create tenants. We are able to create top level tenants. However we try to create a child tenant, we get following error:

>The hasOwnDb parameter is true, but the sharding database name 'SignOn-20240120163734-870' already has tenant(s) using that database. 

Error gives me feeling that for child tenants it is not possible to have their own DB so we tried creating child tenant with `hasOwnDb` property to `true`, `false`, `null` values but above error is coming in all scenarios.

We also tried using `IShardingOnlyTenantAddRemove.CreateTenantAsync` but no avail. Same error.

What are we missing?

**Comment by pradeepgururani** [comment]
Have tried setting `options.TenantType = TenantTypes.HierarchicalTenant | TenantTypes.AddSharding;` as well. With Hierarchical + Sharding we are able to create only top level and no child level.

Is Hierarchical tenancy and sharding mutually exclusive?

**Comment by JonPSmith** [comment]
Hi @pradeepgururani,

OK, you are trying to create a hierarchical multi-tenant in one database, which is fine (Example4 does this). The problem is you need to use the [`IAuthTenantAdminService`](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/AuthPermissions/AdminCode/IAuthTenantAdminService.cs) service. The `IShardingOnlyTenantAddRemove` service is only for a sharding-only tenants.

**Comment by JonPSmith** [comment]
I think you haven't understand the different services used for the two sharding approaches: [hybrid and sharding-only sharding](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Sharding-explained). 

You have selected the hybrid approach so you should use the [IAuthTenantAdminService](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/AuthPermissions/AdminCode/IAuthTenantAdminService.cs) service. The I**ShardingOnly**TenantAddRemove is only for the sharding-only type, so if you give it a tenant that shares a database then it will give you an error.

I recommend you read the article called [The (long) journey to a better sharding multi-tenant application](https://www.thereformedprogrammer.net/the-long-journey-to-a-better-sharding-multi-tenant-application/) which explains that hybrid type has to have manually manages because a tenant's data might be in a database shared by other tenants, or it could have its own database. What I did find that the sharding-only type has only one way to work, so I created the `IShardingOnlyTenantAddRemove` service to make it easier for the developer and admin user.

PS. If you are using [Sign up for a new tenant, with versioning](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Sign-up-for-a-new-tenant%2C-with-versioning) with the hybrid type, then you need to create a `ISignUpGetShardingEntry` that can handle many tenants sharing one database AND tenants that have their own database. The Sign Up documentation has a [section on the `ISignUpGetShardingEntry` with examples](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Sign-up-for-a-new-tenant%2C-with-versioning#isignupgetshardingentry-service)
