### ISSUE TITLE
Invoke app-defined ITenantChangeService from BulkLoadTenantsService.AddTenantsToDatabaseAsync

### ISSUE THREAD

**Issue by Code420SW** [JonPSmith/AuthPermissions.AspNetCore#45]
The app-defined ITenantChangeService is not invoked during the bulk-loading process (from BulkLoadTenantsService.AddTenantsToDatabaseAsync). This leaves the app-specific database (CompanyTenant in Example 3) in an inconsistent state after new tenants are added via the API.

This may be by-design for reasons I don't fully understand. If so, please close this issue. Otherwise, I am happy to pull a PR to address this issue.

**Comment by JonPSmith** [comment]
Hi @Code420SW,

The bulk load is only designed to set up the examples in this repo so that a developer can run an example and it will look like a fully production application. It bypasses a number of things, like ` ITenantChangeService` and doesn't support some things, like sharding.

Therefore Bulk Load shouldn't be used in an production application, apart from one thing: [setting a user on first deployment of a production application](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Bulk-Load-admin#how-to-set-up-a-super-user-when-deploying-a-new-application). The [Bulk Load admin](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Bulk-Load-admin) document didn't make that clear that is the only usage in production so I have updated that document page. 

PS. Thanks for asking before creating a PR.
