### ISSUE TITLE
Can this library work with microservice based solution 

### ISSUE THREAD

**Issue by hassanrazakhalid** [JonPSmith/AuthPermissions.AspNetCore#57]
Hi 
This is not a bug. i just want to verify one use-case. I have 3-4 services and a single authentication service. I need multi-tenancy support in all of them. Will this library be suitable in this scenario and where i can find examples or blogs related to this. Thanks.

**Comment by JonPSmith** [comment]
Hi @hassanrazakhalid,

To make this work with microservices you will need

- The AuthP Roles rely on what I call `Permissions` (see [Permissions explained](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Permissions-explained) doc). You will need to create a project containing the Permissions and every microservices must access this project.
- Your single authentication service will need to also manage the AuthP users Permissions, Roles and Tenants (might like this article about [adding new AuthP users](https://www.thereformedprogrammer.net/three-ways-to-securely-add-new-users-to-an-application-using-the-authp-library/)).
- Your single authentication service must also apply the AuthP claims to the user's `ClaimPrincipal` when they log in (see [AuthUser explained](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/AuthUser-explained)).
- Each microservice will need the AuthP library to a) use the Permissions in the user's claims to control what pages / APIs a user can access and b) to implement the multi-tenants.

The AuthP is complex because multi-tenant apps are complex, but I have written lots of articles and a few videos which describe the issues you face creating a multi-tenant app (see top of sidebar on the [documentation home page](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki). Even if you don't want to use the AuthP libraries there are lots of useful tips in the articles.

Good luck on your project
