### ISSUE TITLE
Error localization / translation feature request

### ISSUE THREAD

**Issue by idan-h** [JonPSmith/AuthPermissions.AspNetCore#58]
Hey, I would like to help refactor the errors in a way that will enable easy translation.   
We can return error code with parmeters instead of string, or use microsoft localization methods.

**Comment by JonPSmith** [comment]
Hi @idan-h,

I already have a library called [EfCore.GenericServices.AspNetCore](https://github.com/JonPSmith/EfCore.GenericServices.AspNetCore) that can convert the errors in a `IStatusGeneric` return into the ASP.NET Core `Model` or a ASP.NET Core Web API - see [this article](https://www.thereformedprogrammer.net/how-to-write-good-testable-asp-net-core-web-api-code-quickly/) on how it works.

Also note that the [`GenericServices.StatusGeneric`](https://github.com/JonPSmith/GenericServices.StatusGeneric) library, which the `IStatusGeneric` comes from, holds errors in the `ValidationResult` class, which can contain the parameter(s) linked to the error text.

In AuthP I use the `IStatusGeneric` on nearly every method, and for any error that is linked to a parameter I set the `MemberNames` parameter in the `ValidationResult` class . For instance, look for the code snippet `status.AddError(` in the AuthP code, e.g.  look at [AuthRolesAdminService](https://github.com/JonPSmith/AuthPermissions.AspNetCore/blob/main/AuthPermissions/AdminCode/Services/AuthRolesAdminService.cs) and you will see me setting the parameter linked to various errors.

What I haven't done is to used the `EfCore.GenericServices.AspNetCore` library the AuthP examples. There is so much code in the repo I take the easy way out and just list all the error messages.  

So, the "return error code with parameters instead of string" is already been handled. I would be interested of how you would "enable easy translation" because I thought that would be done in the ASP.NET Core part, not inside the AuthP library.

**Comment by JonPSmith** [comment]
Hi @idan-h,

I tried the static class for translation but I didn't like it at all, especially when the error message had dynamic parts. So, no I don't want that added to the AuthP library.

If you really want to do something, then creating an example of using the AuthP library with a Blazor frontend is people are asking for. @akema-trebla was looking at this (see issue #38), but think @akema-trebla is too busy to work on it. 

I suggested that a Web API backend + Blazor WASM frontend version of the Example3's multi-tenant project would be great, but its not trivial and its a LOT of work.

**Comment by idan-h** [comment]
I might do that in the future as I am working on blazor wasm project.

I didn't see any implementation of status code of some kind.. Maybe I'm missing something?

Maybe we can add an optional parmeter to the error objects in IStatusGeneric which accepts an Enum or an Integer, which will contain the error code. This way translation will still be easier than looking at the code to find every possible error string and then translating it.

**Comment by JonPSmith** [comment]
> I might do that in the future as I am working on blazor wasm project.

That would be great!

> ... use microsoft localization methods.

You have a point, but its not trivial to create a easy-to-use localization . I'm busy at the moment but I will look at this later.

**Comment by akema-trebla** [comment]
Hi @JonPSmith 

Pardon my tardiness. Yes, I've been quite busy and not been able to deliver as quickly as I'd like. I however have the API implemented and should probably push that.

I made an adjustment to the way we add query filters though, to allow for multiple filters on an entity. Probably should make this a separate issue.

@idan-h how far have you gone with the Blazor sample? Maybe you could pickup from where I left off?

**Comment by idan-h** [comment]
> Hi @JonPSmith 
> 
> Pardon my tardiness. Yes, I've been quite busy and not been able to deliver as quickly as I'd like. I however have the API implemented and should probably push that.
> 
> I made an adjustment to the way we add query filters though, to allow for multiple filters on an entity. Probably should make this a separate issue.
> 
> @idan-h how far have you gone with the Blazor sample? Maybe you could pickup from where I left off? 
> 
> 

I didn't start yet, where did you left off?

**Comment by idan-h** [comment]
> > I might do that in the future as I am working on blazor wasm project.
> 
> That would be great!
> 
> > ... use microsoft localization methods.
> 
> You have a point, but its not trivial to create a easy-to-use localization . I'm busy at the moment but I will look at this later.

Its not very complicated tbh, pretty straight forward with IStringLocalizer and resx files

**Comment by JonPSmith** [comment]
Hi @akema-trebla,

Glad to hear from you. No problem on taking some time on this as no one is getting paid for this. It would be nice if you could add a comment on the original #38 issue on your progress. Also, if you have questions, then use the #38 issue and not this issue. 

> I made an adjustment to the way we add query filters though, to allow for multiple filters on an entity. Probably should make this a separate issue.

If the multiple filters feature is only in your Web API backend project, then that's fine but it mustn't change any of the AuthP library. I work hard to not to change a feature used in previous versions as that effects people who started on a older version. Also keeping the documentation takes a LOT of time.

**Comment by JonPSmith** [comment]
Hi @idan-h, 

> Its not very complicated tbh, pretty straight forward with IStringLocalizer and resx files

I said "its not trivial to create a <ins>easy-to-use</ins> localization".

**Comment by idan-h** [comment]
> easy-to-use

How do you define easy to use?

Does the resx solution combined with dependency injection (IStringLocalizer) suits you?

**Comment by JonPSmith** [comment]
Version 4.1.0 contains localization service - see [this document](https://github.com/JonPSmith/AuthPermissions.AspNetCore/wiki/Languages-&-cultures-explained) for an overview.

**Comment by JonPSmith** [comment]
You might like the feedback on whether adding locational to the AuthP was needed by users - [click this](https://twitter.com/thereformedprog/status/1613904709139726337) to see the Twitter vote on AuthP localization.

**Comment by idan-h** [comment]
> You might like the feedback on whether adding locational to the AuthP was needed by users - [click this](https://twitter.com/thereformedprog/status/1613904709139726337) to see the Twitter vote on AuthP localization.

This is great Jon, thank you! I'm looking forward using it, very much needed.
